name: Forward Port Assets

on:
  push:
    branches:
      - 'release-v*'
    paths:
      - 'assets/**'

jobs:
  forward_port:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Fetches two commits to ensure HEAD~1 is available

      - name: Set up Git config
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Extract assets and versions
        run: |
          echo "::group::Extracting assets and versions"
          for file in $(git diff-tree --no-commit-id --name-only -r HEAD~1 HEAD); do
            if [[ $file == assets/* ]]; then
              filename=$(basename "$file" .tgz)
              assetName=$(echo "$filename" | grep -o '^[^-]*[a-zA-Z]')
              assetVersion=$(echo "$filename" | grep -o '[0-9]+.*')
              echo "Asset Name: $assetName"
              echo "Asset Version: $assetVersion"
            fi
          done
          echo "::endgroup::"
